[workspace]
members = [
    "drivers/windows-driver",
    "drivers/openxr-driver",
    "generator",
    "testing",
    "runtime",
]

[package]
name = "suinput"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "1.0"
