[workspace]
members = [
    "suinput-types",
    "drivers/windows-driver",
    "drivers/sdl2-driver",
    "drivers/openxr-driver",
    # "generator",
    # "bevy_testing",
    "winit_testing",
    "suinput-core",
    "suinput",
]
