[package]
name = "winit_testing"
version = "0.0.1"
edition = "2021"

[dependencies]
suinput = { path = "../" }
runtime = { path = "../runtime" }
windows-driver = { path = "../drivers/windows-driver" }
winit = "0.26"
anyhow = "1.0"
bevy = "0.7.0"
raw-window-handle = "0.4"