[package]
name = "winit_testing"
version = "1.0.0"
edition = "2021"

[dependencies]
suinput = { path = "../suinput" }
windows-driver = { path = "../drivers/windows-driver" }
sdl2-driver = { path = "../drivers/sdl2-driver" }
winit = "0.26"
anyhow = "1.0"
raw-window-handle = "0.4"