[package]
name = "openxr-driver"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
suinput-types = { path = "../../suinput-types" }
thiserror = "1.0"
once_cell = "1.10"
openxr = "0.16"
openxr-sys = "0.9"