[package]
name = "suinput"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
suinput-types = { path = "../suinput-types" }
suinput-core = { path = "../suinput-core" }
flume = "0.10"
parking_lot = "0.12"
raw-window-handle = "0.4"
