[package]
name = "bevy_testing"
version = "1.0.0"
edition = "2021"

[dependencies]
suinput-types = { path = "../suinput-types" }
runtime = { path = "../runtime" }
windows-driver = { path = "../drivers/windows-driver" }
anyhow = "1.0"
bevy = "0.7.0"
raw-window-handle = "0.4"